//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ThirtyOneModel", "PaymentTypeOrders", "PaymentType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ThirtyOne.PaymentType), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ThirtyOne.Order), true)]
[assembly: EdmRelationshipAttribute("ThirtyOneModel", "CustomerOrders", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ThirtyOne.Customer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ThirtyOne.Order), true)]

#endregion

namespace ThirtyOne
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ThirtyOneEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ThirtyOneEntities object using the connection string found in the 'ThirtyOneEntities' section of the application configuration file.
        /// </summary>
        public ThirtyOneEntities() : base("name=ThirtyOneEntities", "ThirtyOneEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ThirtyOneEntities object.
        /// </summary>
        public ThirtyOneEntities(string connectionString) : base(connectionString, "ThirtyOneEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ThirtyOneEntities object.
        /// </summary>
        public ThirtyOneEntities(EntityConnection connection) : base(connection, "ThirtyOneEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaymentType> PaymentTypes
        {
            get
            {
                if ((_PaymentTypes == null))
                {
                    _PaymentTypes = base.CreateObjectSet<PaymentType>("PaymentTypes");
                }
                return _PaymentTypes;
            }
        }
        private ObjectSet<PaymentType> _PaymentTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Party> Parties
        {
            get
            {
                if ((_Parties == null))
                {
                    _Parties = base.CreateObjectSet<Party>("Parties");
                }
                return _Parties;
            }
        }
        private ObjectSet<Party> _Parties;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaymentTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaymentTypes(PaymentType paymentType)
        {
            base.AddObject("PaymentTypes", paymentType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Parties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParties(Party party)
        {
            base.AddObject("Parties", party);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThirtyOneModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="customerName">Initial value of the CustomerName property.</param>
        public static Customer CreateCustomer(global::System.Guid customerID, global::System.String customerName)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.CustomerName = customerName;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Guid _CustomerID;
        partial void OnCustomerIDChanging(global::System.Guid value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ThirtyOneModel", "CustomerOrders", "Order")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("ThirtyOneModel.CustomerOrders", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("ThirtyOneModel.CustomerOrders", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThirtyOneModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="isPaid">Initial value of the IsPaid property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="paymentTypeID">Initial value of the PaymentTypeID property.</param>
        /// <param name="orderDate">Initial value of the OrderDate property.</param>
        public static Order CreateOrder(global::System.Boolean isPaid, global::System.Guid orderID, global::System.Guid customerID, global::System.Guid paymentTypeID, global::System.DateTime orderDate)
        {
            Order order = new Order();
            order.IsPaid = isPaid;
            order.OrderID = orderID;
            order.CustomerID = customerID;
            order.PaymentTypeID = paymentTypeID;
            order.OrderDate = orderDate;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OrderSubTotal
        {
            get
            {
                return _OrderSubTotal;
            }
            set
            {
                OnOrderSubTotalChanging(value);
                ReportPropertyChanging("OrderSubTotal");
                _OrderSubTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderSubTotal");
                OnOrderSubTotalChanged();
            }
        }
        private Nullable<global::System.Double> _OrderSubTotal;
        partial void OnOrderSubTotalChanging(Nullable<global::System.Double> value);
        partial void OnOrderSubTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OrderTax
        {
            get
            {
                return _OrderTax;
            }
            set
            {
                OnOrderTaxChanging(value);
                ReportPropertyChanging("OrderTax");
                _OrderTax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderTax");
                OnOrderTaxChanged();
            }
        }
        private Nullable<global::System.Double> _OrderTax;
        partial void OnOrderTaxChanging(Nullable<global::System.Double> value);
        partial void OnOrderTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OrderTotal
        {
            get
            {
                return _OrderTotal;
            }
            set
            {
                OnOrderTotalChanging(value);
                ReportPropertyChanging("OrderTotal");
                _OrderTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderTotal");
                OnOrderTotalChanged();
            }
        }
        private Nullable<global::System.Double> _OrderTotal;
        partial void OnOrderTotalChanging(Nullable<global::System.Double> value);
        partial void OnOrderTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPaid
        {
            get
            {
                return _IsPaid;
            }
            set
            {
                OnIsPaidChanging(value);
                ReportPropertyChanging("IsPaid");
                _IsPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPaid");
                OnIsPaidChanged();
            }
        }
        private global::System.Boolean _IsPaid;
        partial void OnIsPaidChanging(global::System.Boolean value);
        partial void OnIsPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Guid _OrderID;
        partial void OnOrderIDChanging(global::System.Guid value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.Guid _CustomerID;
        partial void OnCustomerIDChanging(global::System.Guid value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PaymentTypeID
        {
            get
            {
                return _PaymentTypeID;
            }
            set
            {
                OnPaymentTypeIDChanging(value);
                ReportPropertyChanging("PaymentTypeID");
                _PaymentTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentTypeID");
                OnPaymentTypeIDChanged();
            }
        }
        private global::System.Guid _PaymentTypeID;
        partial void OnPaymentTypeIDChanging(global::System.Guid value);
        partial void OnPaymentTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> PartyID
        {
            get
            {
                return _PartyID;
            }
            set
            {
                OnPartyIDChanging(value);
                ReportPropertyChanging("PartyID");
                _PartyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartyID");
                OnPartyIDChanged();
            }
        }
        private Nullable<global::System.Guid> _PartyID;
        partial void OnPartyIDChanging(Nullable<global::System.Guid> value);
        partial void OnPartyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OrderShipping
        {
            get
            {
                return _OrderShipping;
            }
            set
            {
                OnOrderShippingChanging(value);
                ReportPropertyChanging("OrderShipping");
                _OrderShipping = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderShipping");
                OnOrderShippingChanged();
            }
        }
        private Nullable<global::System.Double> _OrderShipping;
        partial void OnOrderShippingChanging(Nullable<global::System.Double> value);
        partial void OnOrderShippingChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ThirtyOneModel", "PaymentTypeOrders", "PaymentType")]
        public PaymentType PaymentType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PaymentType>("ThirtyOneModel.PaymentTypeOrders", "PaymentType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PaymentType>("ThirtyOneModel.PaymentTypeOrders", "PaymentType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PaymentType> PaymentTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PaymentType>("ThirtyOneModel.PaymentTypeOrders", "PaymentType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PaymentType>("ThirtyOneModel.PaymentTypeOrders", "PaymentType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ThirtyOneModel", "CustomerOrders", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("ThirtyOneModel.CustomerOrders", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("ThirtyOneModel.CustomerOrders", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("ThirtyOneModel.CustomerOrders", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("ThirtyOneModel.CustomerOrders", "Customer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThirtyOneModel", Name="Party")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Party : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Party object.
        /// </summary>
        /// <param name="partyID">Initial value of the PartyID property.</param>
        /// <param name="partyDate">Initial value of the PartyDate property.</param>
        /// <param name="partyTotal">Initial value of the PartyTotal property.</param>
        public static Party CreateParty(global::System.Guid partyID, global::System.DateTime partyDate, global::System.Double partyTotal)
        {
            Party party = new Party();
            party.PartyID = partyID;
            party.PartyDate = partyDate;
            party.PartyTotal = partyTotal;
            return party;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PartyID
        {
            get
            {
                return _PartyID;
            }
            set
            {
                if (_PartyID != value)
                {
                    OnPartyIDChanging(value);
                    ReportPropertyChanging("PartyID");
                    _PartyID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PartyID");
                    OnPartyIDChanged();
                }
            }
        }
        private global::System.Guid _PartyID;
        partial void OnPartyIDChanging(global::System.Guid value);
        partial void OnPartyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PartyDate
        {
            get
            {
                return _PartyDate;
            }
            set
            {
                OnPartyDateChanging(value);
                ReportPropertyChanging("PartyDate");
                _PartyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartyDate");
                OnPartyDateChanged();
            }
        }
        private global::System.DateTime _PartyDate;
        partial void OnPartyDateChanging(global::System.DateTime value);
        partial void OnPartyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double PartyTotal
        {
            get
            {
                return _PartyTotal;
            }
            set
            {
                OnPartyTotalChanging(value);
                ReportPropertyChanging("PartyTotal");
                _PartyTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartyTotal");
                OnPartyTotalChanged();
            }
        }
        private global::System.Double _PartyTotal;
        partial void OnPartyTotalChanging(global::System.Double value);
        partial void OnPartyTotalChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ThirtyOneModel", Name="PaymentType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaymentType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaymentType object.
        /// </summary>
        /// <param name="paymentTypeID">Initial value of the PaymentTypeID property.</param>
        public static PaymentType CreatePaymentType(global::System.Guid paymentTypeID)
        {
            PaymentType paymentType = new PaymentType();
            paymentType.PaymentTypeID = paymentTypeID;
            return paymentType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentTypeName
        {
            get
            {
                return _PaymentTypeName;
            }
            set
            {
                OnPaymentTypeNameChanging(value);
                ReportPropertyChanging("PaymentTypeName");
                _PaymentTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaymentTypeName");
                OnPaymentTypeNameChanged();
            }
        }
        private global::System.String _PaymentTypeName;
        partial void OnPaymentTypeNameChanging(global::System.String value);
        partial void OnPaymentTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PaymentTypeID
        {
            get
            {
                return _PaymentTypeID;
            }
            set
            {
                if (_PaymentTypeID != value)
                {
                    OnPaymentTypeIDChanging(value);
                    ReportPropertyChanging("PaymentTypeID");
                    _PaymentTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaymentTypeID");
                    OnPaymentTypeIDChanged();
                }
            }
        }
        private global::System.Guid _PaymentTypeID;
        partial void OnPaymentTypeIDChanging(global::System.Guid value);
        partial void OnPaymentTypeIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ThirtyOneModel", "PaymentTypeOrders", "Order")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("ThirtyOneModel.PaymentTypeOrders", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("ThirtyOneModel.PaymentTypeOrders", "Order", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
